Upgrade to latest abp2dnr
ghostery/urlfilter2dnr pull request #11
Opened 2024-01-02 09:38 UTC by seia-soto

Fixes #9

## Summary

- Upgrade from `@ghostery/abp2dnr` to `@eyeo/abp2dnr`
- Patched `@eyeo/abp2dnr` not to use Node native binding
- Update test cases
- One test cannot be fixed (TrackerDB filters)

### Patched `@eyeo/abp2dnr` not to use Node native bindings

New module uses Node native bindings that cannot be used with Bunjs. Unfortunately, the use of native module removed. `../build/Release/isRegexSupported` refers to the file `../build/Release/isRegexSupported.node`.

```diff
diff --git a/node_modules/@eyeo/abp2dnr/lib/converter.js b/node_modules/@eyeo/abp2dnr/lib/converter.js
index e284b0e..69e49c2 100644
--- a/node_modules/@eyeo/abp2dnr/lib/converter.js
+++ b/node_modules/@eyeo/abp2dnr/lib/converter.js
@@ -19,14 +19,12 @@
 
 "use strict";
 
-const {isRegexSupported} = require("../build/Release/isRegexSupported");
 const {createConverter} = require("@eyeo/webext-ad-filtering-solution/adblockpluscore/lib/dnr/index.js");
 const {FilterParsingError} = require("@eyeo/webext-ad-filtering-solution/adblockpluscore/lib/filters/index.js");
 const {Filter} = require("@eyeo/webext-ad-filtering-solution/adblockpluscore/lib/filterClasses.js");
 
 function regexCheck(r) {
-  let result = isRegexSupported(r);
-  return result.isSupported;
+  return false;
 }
 
 let converter = createConverter({isRegexSupported: regexCheck});
```

### TrackerDB filters test cannot be fixed

TrackerDB filters test failed but it's not resolvable anymore. Before this changes, `normalize` function from `test/unit/helpers.js` normalized the output rule. However, it doesn't work anymore as abp2dnr throws empty array ([]) instead of partial rule ([truthy value]).

I suggest to skip testing rules leading to incomplete comparison.

2024-01-03 11:59 UTC, chrmod requested changes

2024-01-03 11:59 UTC, chrmod commented on test/unit/converters/abp.spec.js
> -        initiatorDomains: [
need to address this

2024-01-03 12:00 UTC, chrmod commented
We should ensure that all TrackerDB tests pass. The point of this project is to ensure different converters behave the same.

2024-01-04 07:33 UTC, seia-soto commented on test/unit/converters/abp.spec.js
> -        initiatorDomains: [
I pushed a commit to normalize legacy properties on DNR: https://developer.chrome.com/docs/extensions/reference/api/declarativeNetRequest#property-RuleCondition-excludedInitiatorDomains

2024-01-04 09:03 UTC, chrmod approved these changes

2024-01-04 09:03 UTC, chrmod approved these changes

2024-01-04 09:04 UTC, merged